### ISSUE TITLE
从QQ分享链接后打开会自动加上“&tdsourcetag=s_pctim_aiomsg”

### ISSUE THREAD

**Issue by wyfang** [mengkunsoft/lmbtfy#4]
当然这个是QQ的问题，那么又没办法做到屏蔽这个呢？

**Comment by mengkunsoft** [comment]
这个问题我也发现了……现在有两种方案：
一种是改变获取搜索词的方式（一劳永逸，但会导致以前生成的链接失效）
另一种是过滤掉这段内容（实现起来不够优雅）

**Comment by wyfang** [comment]
@mengkunsoft 一劳永逸好啊，我刚使用，如何可以单独提供这个解决方法，那非常完美。

**Comment by mengkunsoft** [comment]
新版已一劳永逸地解决了这个问题……当然，如果之前使用的是旧版，现在改用新版，会导致以前生成的链接失效
